branches:
    only:
        - master
skip_tags: true
matrix:
    fast_finish: true
install:
    - git submodule update --init --recursive
build_script:
    - mkdir out_debug
    - cd out_debug
    - cmake ../src
    - cmake --build . --config Debug
    - cd ..
    - mkdir out_release
    - cd out_release
    - cmake ../src
    - cmake --build . --config Release
notifications:
    - provider: Email
      to:
        - m@bitsnbites.eu
    - on_build_failure: true
    - on_build_success: false

