language: cpp
compiler:
    - clang
    - gcc
branches:
    only:
        - master
os:
    - linux
    - osx
sudo: required
dist: trusty
before_install:
    - tools/install-deps.sh
script:
    - tools/static-analysis.sh
    - mkdir out_debug
    - cd out_debug
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ../src
    - cmake --build .
    - cd ..
    - mkdir out_release
    - cd out_release
    - cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../src
    - cmake --build .
notifications:
    email:
        recipients:
            - m@bitsnbites.eu
    on_success: never
    on_failure: always

